### ISSUE TITLE
feat: Image Upscaler

### ISSUE THREAD

**Issue by jinlee0** [Liberty52/product#256]
후보
- [LetsEnhance.io](https://letsenhance.io/) & [Claid.ai](https://claid.ai/)
- [Stability AI’s Image Upscaling API](https://platform.stability.ai/docs/features/image-upscaling?tab=typescript)
- [DeepAI’s Super Resolution API](https://deepai.org/machine-learning-model/torch-srgan)
- [ClipDrop's Super Resolution API](https://clipdrop.co/apis/docs/super-resolution)
- [Ximilar](https://www.ximilar.com/)
- [VanceAI API](https://vanceai.com/api/)
- [DeepImage's API](https://deep-image.ai/app/api-documentation/)

<details>
<summary>비용 예시</summary>
<div markdown="1">
LetsEnhance.id & Claid.ai

![image](https://github.com/Liberty52/product/assets/74762475/b9223ae1-5f64-4ea8-bab1-a99971da08e5)
![image](https://github.com/Liberty52/product/assets/74762475/10043d8e-176c-4845-9e35-2426948ddf36)

Stability
![image](https://github.com/Liberty52/product/assets/74762475/5ab571a0-5c7a-4d83-8836-0765de016f2c)

</div>
</details>

[LetsEnhance.io](https://letsenhance.io/)에 따르면, 500메가픽셀, 300dpi 이상도 되는 듯 합니다. 하지만 결제 단위가 크고 API 사용은 wait-list를 걸어야 하는 듯 합니다.

일단 Staibility로 구현해보겠습니다.

API:
```yaml
method: POST
url: /images/upscaling

request-body:
  url: string # image url to upscale
  scale: number # 2 for X2, 3 for X3, 4 for X4
```
